<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>NoteTaker.Data</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.29" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NoteTaker.Core\NoteTaker.Core.csproj" />
  </ItemGroup>

</Project>
